"""Generate and validate one deterministic reproduction notebook per canonical Parquet."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections import Counter
from pathlib import Path
from typing import Any

import nbformat

from reproduce.build_parquet_reproduction_registry import (
    CATALOG_PATH,
    REGISTRY_PATH,
    ROOT,
    STATUSES,
    build_registry,
)

OUTPUT_DIR = ROOT / "notebooks/reproduce"
README_PATH = OUTPUT_DIR / "README.md"
GENERATED_MARKER = "Generated by reproduce/generate_parquet_reproduction_notebooks.py; do not edit."


def _cell_id(index: int, source: str) -> str:
    return hashlib.sha256(f"{index}:{source}".encode()).hexdigest()[:12]


def _bullet(values: list[str], *, empty: str) -> str:
    return "\n".join(f"- `{value}`" for value in values) if values else f"- {empty}"


def _fields_table(fields: list[dict[str, Any]]) -> str:
    rows = ["| Column | Arrow dtype | Nullable |", "|---|---|---:|"]
    rows.extend(f"| `{f['name']}` | `{f['dtype']}` | `{str(f['nullable']).lower()}` |" for f in fields)
    return "\n".join(rows)


def _keys(record: dict[str, Any]) -> str:
    keys = record["keys"]
    return (
        f"- Source-contract key: {', '.join(f'`{v}`' for v in keys['source_contract']) or 'none declared'}\n"
        f"- Candidate/join key: {', '.join(f'`{v}`' for v in keys['candidate_join']) or 'none declared'}\n"
        f"- Linkage: {', '.join(f'`{v}`' for v in keys['linkage']) or 'none declared'}\n"
        f"- Uniqueness note: {keys['uniqueness']}"
    )


def _receipt(record: dict[str, Any]) -> str:
    receipt = record["migration_receipt"]
    sources = receipt.get("sources", [receipt.get("source")])
    source_lines = "\n".join(f"  - `{value}`" for value in sources if value)
    return (
        f"- Action: `{receipt['action']}`\n"
        f"- Preserved pre-migration source object(s):\n{source_lines}\n"
        f"- Destination generation: `{receipt['destination_generation']}`\n"
        f"- Destination CRC32C: `{receipt['destination_crc32c']}`\n"
        f"- Verified migration readback: `{receipt['verified']}`"
        + (f"\n- Destination SHA-256: `{receipt['destination_sha256']}`" if receipt.get("destination_sha256") else "")
    )


def build_notebook(record: dict[str, Any]) -> nbformat.NotebookNode:
    dataset_id = f"{record['layer']}__{record['name']}"
    qc = record["qc"]
    command = record["full_worker_rebuild_command"]
    command_text = (
        f"```text\n{command}\n```\n\nThis exact argv is preserved as documentation only. It must run on an approved in-region worker, against worker-local verified inputs, with task-local staging and review before any canonical write."
        if command
        else "No verified exact full rebuild command is available. The lineage registry deliberately leaves this gap explicit rather than synthesizing an argv."
    )
    intro = f"""# Reproduce `{dataset_id}`

{GENERATED_MARKER}

## Objective and meaning

Document and safely verify the exact current canonical Parquet `{record['canonical_uri']}`.

**Meaning:** {record['meaning']}

**Does not mean:** {record['non_meaning']}

- Catalog: [`{record['catalog_page']}`](../../{record['catalog_page']})
- Canonical URI: `{record['canonical_uri']}`
- Reproducibility status: **`{record['reproducibility_status']}`**
- Source family: **{record['source_family_label']}** (`{record['source_family']}`)
"""
    lineage = f"""## Native inputs, release, acquisition and environment

**Release/version:** {record['release']}

**Known retained raw objects or source endpoints**

{_bullet(record['native_inputs'], empty='No selected native input is retained or resolvable from current evidence.')}

**Preconditions:** {record['acquisition_and_preconditions']}

## Expected schema and identifiers

- Expected rows: **{qc['rows']:,}**
- Expected bytes: **{qc['bytes']:,}**
- Expected row groups: **{qc['row_groups']}**
- Schema hash (`{qc['schema_hash_version']}`): `{qc['schema_hash']}`
- Object generation: `{qc['generation']}`
- CRC32C (base64): `{qc['crc32c_base64']}`

{_fields_table(record['fields'])}

## Keys, mappings and joins

{_keys(record)}

{record['mappings_and_joins']}

## Cleaning, normalization, transformations and filters

{record['transformations_and_filters']}

## Deduplication and assertion/evidence semantics

{record['deduplication_and_evidence']}

## Quarantines, exclusions and missing data

{record['quarantines_exclusions_missing']}

## Problems encountered and decisions

{record['problems_and_decisions']}

Provenance fields still missing for this record: {', '.join(f'`{value}`' for value in record['provenance_gaps']) or 'none declared'}.

## Producer / builder

Tracked producer: `{record['producer_builder'] or 'not available as a current tracked builder'}`.

## Full worker rebuild command (inert text; never executed by this notebook)

{command_text}

## Migration receipt

{_receipt(record)}

## QC, bounded replay and verification

{record['safe_bounded_replay']}

The first code cell below performs an offline contract check only. The second is opt-in and reads GCS object metadata plus the Parquet footer only; it requires caller-owned ADC and `JOUVENCE_BILLING_PROJECT`. Neither cell writes data.

## Reproducibility limits

{record['reproducibility_limits']}

## Linked code, tests, reports and historical notebooks

{_bullet(record['links'], empty='No additional tracked links.')}
"""
    embedded = json.dumps(record, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    offline_code = f'''import hashlib
import json

RECORD = json.loads(r\'''{embedded}\''')

def require(condition, message):
    if not condition:
        raise RuntimeError(message)

require(RECORD["canonical_uri"] == "gs://jouvencekb/main/" + ("embeddings" if RECORD["layer"] == "embedding" else RECORD["layer"]) + "/" + RECORD["name"] + ".parquet", "canonical URI/identity mismatch")
require(RECORD["reproducibility_status"] in {sorted(STATUSES)!r}, "unsupported reproducibility status")
require(RECORD["qc"]["rows"] >= 0, "negative expected row count")
require(len(RECORD["qc"]["schema_hash"]) == 64, "invalid schema hash")
require(RECORD["migration_receipt"]["verified"] is True, "migration receipt is not verified")
require(bool(RECORD["fields"]), "empty expected schema")
summary = {{
    "identity": RECORD["layer"] + "__" + RECORD["name"],
    "rows": RECORD["qc"]["rows"],
    "status": RECORD["reproducibility_status"],
    "schema_hash": RECORD["qc"]["schema_hash"],
}}
summary
'''
    live_code = '''import os

if os.environ.get("JOUVENCE_LIVE_GCS") != "1":
    live_result = {"status": "SKIPPED", "reason": "set JOUVENCE_LIVE_GCS=1 and caller-owned JOUVENCE_BILLING_PROJECT"}
else:
    import gcsfs
    import pyarrow.parquet as pq

    billing_project = os.environ.get("JOUVENCE_BILLING_PROJECT")
    if not billing_project:
        raise RuntimeError("JOUVENCE_BILLING_PROJECT is required for requester-pays live verification")
    fs = gcsfs.GCSFileSystem(project=billing_project, requester_pays=billing_project, version_aware=True)
    if not fs.version_aware:
        raise RuntimeError("version-aware GCS reads are required")
    object_path = RECORD["canonical_uri"].removeprefix("gs://")
    if "#" in object_path:
        raise RuntimeError("canonical object key must not already contain a generation suffix")
    expected_generation = RECORD["qc"]["generation"]
    pinned_path = object_path + "#" + expected_generation
    info = fs.info(pinned_path)
    if str(info.get("generation", "")) != expected_generation:
        raise RuntimeError("generation-qualified object resolved a different generation")
    with fs.open(pinned_path, "rb") as handle:
        parquet = pq.ParquetFile(handle)
        live_fields = [
            {"name": field.name, "dtype": str(field.type), "nullable": bool(field.nullable)}
            for field in parquet.schema_arrow
        ]
        live_rows = parquet.metadata.num_rows
        live_row_groups = parquet.metadata.num_row_groups
    if live_rows != RECORD["qc"]["rows"]:
        raise RuntimeError("live footer row count differs from the frozen registry")
    if live_row_groups != RECORD["qc"]["row_groups"]:
        raise RuntimeError("live footer row-group count differs from the frozen registry")
    if live_fields != RECORD["fields"]:
        raise RuntimeError("live footer schema differs from the frozen registry")
    live_result = {"status": "PASS", "generation": str(info["generation"]), "rows": live_rows, "row_groups": live_row_groups}
live_result
'''
    notebook = nbformat.v4.new_notebook(
        cells=[
            nbformat.v4.new_markdown_cell(intro),
            nbformat.v4.new_markdown_cell(lineage),
            nbformat.v4.new_markdown_cell("## Offline bounded contract check\n\nThis cell uses only the embedded frozen lineage record."),
            nbformat.v4.new_code_cell(offline_code),
            nbformat.v4.new_markdown_cell("## Optional bounded live canonical footer check\n\nThis cell is skipped unless the caller explicitly opts in."),
            nbformat.v4.new_code_cell(live_code),
        ],
        metadata={
            "kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
    )
    for index, cell in enumerate(notebook.cells):
        cell.id = _cell_id(index, cell.source)
        if cell.cell_type == "code":
            cell.execution_count = None
            cell.outputs = []
    return notebook


def build_readme(registry: dict[str, Any]) -> str:
    records = registry["records"]
    counts = Counter(row["reproducibility_status"] for row in records)
    lines = [
        "# Exact canonical Parquet reproduction notebooks",
        "",
        GENERATED_MARKER,
        "",
        "This directory has exactly one generated, read-only-by-default notebook for every current canonical Parquet in `gs://jouvencekb/main`. The exact denominator and identity spelling come from `docs/parquet-catalog/inventory.json`; `embedding` is intentionally singular here because that is the catalog layer identity even though its GCS prefix is `embeddings/`.",
        "",
        "These notebooks preserve and link the broader historical `reproduce/*.ipynb` source-family notebooks. A family notebook or byte-preserving migration receipt is not, by itself, proof that the original biological build is fully replayable.",
        "",
        "## Status summary",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    lines.extend(f"| `{status}` | {counts.get(status, 0)} |" for status in sorted(STATUSES))
    lines.extend([
        "",
        "## Safety and regeneration",
        "",
        "- Default execution is offline and validates only the embedded registry/receipt contract.",
        "- Live verification is opt-in with `JOUVENCE_LIVE_GCS=1` plus caller-owned `JOUVENCE_BILLING_PROJECT`; it reads metadata and a Parquet footer only.",
        "- Full rebuild commands are inert Markdown and remain worker-only/canonical-write-gated.",
        "- Regenerate: `uv run python reproduce/build_parquet_reproduction_registry.py && uv run python reproduce/generate_parquet_reproduction_notebooks.py`.",
        "- Check: `uv run python reproduce/generate_parquet_reproduction_notebooks.py --check`.",
        "",
        "## Notebook index",
        "",
        "| Layer | Dataset | Source family | Status | Rows | Notebook | Catalog |",
        "|---|---|---|---|---:|---|---|",
    ])
    for row in records:
        dataset_id = f"{row['layer']}__{row['name']}"
        lines.append(
            f"| `{row['layer']}` | `{row['name']}` | {row['source_family_label']} | `{row['reproducibility_status']}` | {row['qc']['rows']:,} | [{dataset_id}.ipynb]({dataset_id}.ipynb) | [catalog](../../{row['catalog_page']}) |"
        )
    return "\n".join(lines) + "\n"


def validate_registry(registry: dict[str, Any]) -> None:
    catalog = json.loads(CATALOG_PATH.read_text())
    expected = {(row["layer"], row["name"]) for row in catalog["datasets"]}
    actual = [(row["layer"], row["name"]) for row in registry["records"]]
    if len(actual) != len(set(actual)):
        raise SystemExit("duplicate lineage registry identities")
    if set(actual) != expected:
        raise SystemExit(f"registry/catalog mismatch: missing={sorted(expected - set(actual))}, stale={sorted(set(actual) - expected)}")
    if registry["record_count"] != len(actual) or len(actual) != catalog["dataset_count"]:
        raise SystemExit("registry count does not equal catalog denominator")
    for row in registry["records"]:
        if row["reproducibility_status"] not in STATUSES:
            raise SystemExit(f"invalid status: {row['reproducibility_status']}")
        if row["reproducibility_status"] == "fully-replayable":
            required = (row["native_inputs"], row["producer_builder"], row["full_worker_rebuild_command"], row["rebuild_command_evidenced"])
            if not all(required):
                raise SystemExit(f"overstated fully-replayable record: {row['layer']}__{row['name']}")
        for link in row["links"]:
            if link.startswith(("docs/", "reproduce/", "manage_db/", "tests/")) and not (ROOT / link).exists():
                raise SystemExit(f"missing tracked link for {row['layer']}__{row['name']}: {link}")
        receipt = row["migration_receipt"]
        if not receipt.get("verified") or receipt["destination_generation"] != row["qc"]["generation"]:
            raise SystemExit(f"inventory/migration receipt mismatch: {row['layer']}__{row['name']}")


def expected_files(registry: dict[str, Any]) -> dict[Path, str]:
    files = {README_PATH: build_readme(registry)}
    for row in registry["records"]:
        path = ROOT / row["notebook"]
        files[path] = nbformat.writes(build_notebook(row))
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if registry or generated files are stale")
    args = parser.parse_args(argv)
    expected_registry = build_registry()
    if not REGISTRY_PATH.exists():
        if args.check:
            raise SystemExit(f"missing registry: {REGISTRY_PATH.relative_to(ROOT)}")
        REGISTRY_PATH.write_text(json.dumps(expected_registry, indent=2, sort_keys=True) + "\n")
    actual_registry = json.loads(REGISTRY_PATH.read_text())
    if actual_registry != expected_registry:
        if args.check:
            raise SystemExit("stale parquet reproduction lineage registry")
        REGISTRY_PATH.write_text(json.dumps(expected_registry, indent=2, sort_keys=True) + "\n")
        actual_registry = expected_registry
    validate_registry(actual_registry)
    files = expected_files(actual_registry)
    expected_notebooks = {path for path in files if path.suffix == ".ipynb"}
    existing_notebooks = set(OUTPUT_DIR.glob("*.ipynb")) if OUTPUT_DIR.exists() else set()
    if args.check:
        if existing_notebooks != expected_notebooks:
            raise SystemExit(f"generated notebook path mismatch: missing={sorted(str(p.relative_to(ROOT)) for p in expected_notebooks-existing_notebooks)}, stale={sorted(str(p.relative_to(ROOT)) for p in existing_notebooks-expected_notebooks)}")
        stale = [path.relative_to(ROOT).as_posix() for path, content in files.items() if not path.exists() or path.read_text() != content]
        if stale:
            raise SystemExit(f"stale generated reproduction files: {stale}")
        return 0
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in existing_notebooks - expected_notebooks:
        path.unlink()
    for path, content in files.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
